/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: uno.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./uno_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UnoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UnoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.JoinRequest,
 *   !proto.JoinResponse>}
 */
const methodDescriptor_UnoService_JoinGame = new grpc.web.MethodDescriptor(
  '/UnoService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.JoinRequest,
  proto.JoinResponse,
  /**
   * @param {!proto.JoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.JoinResponse.deserializeBinary
);


/**
 * @param {!proto.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.JoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.JoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UnoServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UnoService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_UnoService_JoinGame,
      callback);
};


/**
 * @param {!proto.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.JoinResponse>}
 *     Promise that resolves to the response
 */
proto.UnoServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UnoService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_UnoService_JoinGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GameStateRequest,
 *   !proto.GameStateResponse>}
 */
const methodDescriptor_UnoService_GameState = new grpc.web.MethodDescriptor(
  '/UnoService/GameState',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.GameStateRequest,
  proto.GameStateResponse,
  /**
   * @param {!proto.GameStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.GameStateResponse.deserializeBinary
);


/**
 * @param {!proto.GameStateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.GameStateResponse>}
 *     The XHR Node Readable Stream
 */
proto.UnoServiceClient.prototype.gameState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/UnoService/GameState',
      request,
      metadata || {},
      methodDescriptor_UnoService_GameState);
};


/**
 * @param {!proto.GameStateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.GameStateResponse>}
 *     The XHR Node Readable Stream
 */
proto.UnoServicePromiseClient.prototype.gameState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/UnoService/GameState',
      request,
      metadata || {},
      methodDescriptor_UnoService_GameState);
};


module.exports = proto;

