/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: streaming_demo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as streaming_demo_pb from './streaming_demo_pb'; // proto import: "streaming_demo.proto"


export class DemoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUnaryCall = new grpcWeb.MethodDescriptor(
    '/DemoService/UnaryCall',
    grpcWeb.MethodType.UNARY,
    streaming_demo_pb.UnaryRequest,
    streaming_demo_pb.UnaryResponse,
    (request: streaming_demo_pb.UnaryRequest) => {
      return request.serializeBinary();
    },
    streaming_demo_pb.UnaryResponse.deserializeBinary
  );

  unaryCall(
    request: streaming_demo_pb.UnaryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<streaming_demo_pb.UnaryResponse>;

  unaryCall(
    request: streaming_demo_pb.UnaryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: streaming_demo_pb.UnaryResponse) => void): grpcWeb.ClientReadableStream<streaming_demo_pb.UnaryResponse>;

  unaryCall(
    request: streaming_demo_pb.UnaryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: streaming_demo_pb.UnaryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/DemoService/UnaryCall',
        request,
        metadata || {},
        this.methodDescriptorUnaryCall,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/DemoService/UnaryCall',
    request,
    metadata || {},
    this.methodDescriptorUnaryCall);
  }

  methodDescriptorServerStreamingCall = new grpcWeb.MethodDescriptor(
    '/DemoService/ServerStreamingCall',
    grpcWeb.MethodType.SERVER_STREAMING,
    streaming_demo_pb.ServerStreamingRequest,
    streaming_demo_pb.ServerStreamingResponse,
    (request: streaming_demo_pb.ServerStreamingRequest) => {
      return request.serializeBinary();
    },
    streaming_demo_pb.ServerStreamingResponse.deserializeBinary
  );

  serverStreamingCall(
    request: streaming_demo_pb.ServerStreamingRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<streaming_demo_pb.ServerStreamingResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/DemoService/ServerStreamingCall',
      request,
      metadata || {},
      this.methodDescriptorServerStreamingCall);
  }

}

